### ISSUE TITLE
i3wm bug

### ISSUE THREAD

**Issue by newyorkthink** [felixfung/skippy-xd#134]
![image](https://github.com/user-attachments/assets/9e235123-8bc8-4f6c-aca8-5d8b6e9d6f8b)

when i reload i3wm ,cannot run, just have process

**Comment by felixfung** [comment]
Please try `killall skippy-xd` then try again

**Comment by newyorkthink** [comment]
> Please try `killall skippy-xd` then try again

is not working, i try this

**Comment by felixfung** [comment]
Please report in detail the steps you did

**Comment by newyorkthink** [comment]
> Please report in detail the steps you did

i don't not how to make this

**Comment by felixfung** [comment]
Without detailed report I'll close your issues. Thanks
