### ISSUE TITLE
the freq is too fast

### ISSUE THREAD

**Issue by newyorkthink** [felixfung/skippy-xd#135]
Uploading freecompress-20240915_123028.mp4…

**Comment by newyorkthink** [comment]
https://github.com/user-attachments/assets/79a4a7fc-7e0b-4b34-8165-840acdaad1d9

**Comment by newyorkthink** [comment]
@felixfung look this, is have glisten

**Comment by felixfung** [comment]
This is known issue #84. To mitigate please use picom
