### ISSUE TITLE
something preview is not show

### ISSUE THREAD

**Issue by newyorkthink** [felixfung/skippy-xd#147]
![image](https://github.com/user-attachments/assets/36bed4be-f316-4620-8460-0b702f17c0d3)

**Comment by newyorkthink** [comment]
> https://github.com/felixfung/skippy-xd/wiki/Usage#some-windows-are-not-showing-or-showing-extra-windows-or-the-window-z-order-is-wrong

itried XQueryTree、_NET_CLIENT_LIST  _WIN_CLIENT_LIST。 ,is have this bug in i3wm

**Comment by felixfung** [comment]
https://youtu.be/lS33Z2s8xrs

I have a YouTube video using i3 with no issues and full config file explanation
