### ISSUE TITLE
Whiskermenu in skippy-xd --expose

### ISSUE THREAD

**Issue by Ikuyu** [felixfung/skippy-xd#149]
The Whisker Menu is shown as an open app/window in skippy-xd --expose.
It's a black rectangle, sometimes grey, now and then grey and black together.
It should not be visible, right?

Is there a fix for this?

System: Fedora 41 XFCE spin running on a macbook pro mid 2012.

**Comment by felixfung** [comment]
I am guessing it is the same issue as the comment in https://www.youtube.com/watch?v=R__zua04xe0?

Please try in the config file:
```
clientList = _NET_CLIENT_LIST
```

**Comment by Ikuyu** [comment]
Solved it by copying the sample config file to ~/.config/skippy-xd/skippy-xd.rc. Thanks.

**Comment by felixfung** [comment]
Wondering what is `clientList` in your config file?

**Comment by Ikuyu** [comment]
clientList = XQueryTree

**Comment by felixfung** [comment]
Ok, perhaps it was some filtering options that was messed up. Anyway if your problem is solved please feel free to close fix comment. Thanks!

**Comment by Ikuyu** [comment]
Issue reoccurred. Updated the string `clientList = XQueryTree` to `clientList = _NET_CLIENT_LIST`. Issue seems fixed now. Thanks again. Nice app. Keep up the good work!
