### ISSUE TITLE
Failed to open pipe "/tmp/skippy-xd-fifo-3"

### ISSUE THREAD

**Issue by tonywhatever** [felixfung/skippy-xd#151]
skippy-xd-0.8.0

Problem:
'skippy-xd --start-daemon' emits the following message:

open_pipe(): Failed to open pipe "/tmp/skippy-xd-fifo-3": 13
open: Permission denied

Description:
If 'User A' has logged out of his account and a new 'User B' logs in to start the GUI, skippy-xd fails to start because the pipe left behind by the previous instant of 'skippy-xd  --start-daemon' is owned by the 'User A' and can not be used or removed by the new 'User B'.

At the moment I use a DM with a cleanup-script to take care of the abandoned pipe. If the GUI is started via 'startx' it is more difficult to get rid of that pipe owned by the previous User.

Request:
Please make 'skippy-xd --start-daemon' to remove the pipe before it exits. (trap command in bash)

Thank you

**Comment by felixfung** [comment]
A user should not deleting the pipe of another user.

```
skippy-xd --stop-daemon
```
deletes the pipe.

Can you please try PR #152, which adds the user ID to the name of the pipe? This way one user instance of skippy-xd would not block another.

**Comment by tonywhatever** [comment]
Yes, skippy-xd --stop-daemon does remove the pipe but sending an interrupt/terminate signal to the running skippy-xd daemon does not remove the pipe which is owned by the logout-user.

So, if I logout and xfce4 closes down - the pipe does not get removed by skippy-xd because obviously xfce does not terminate the daemon with 'skippy-xd --stop-daemon'. In my opinion, skippy daemon must be made aware that when it receives a interrupt/term signal that it has to remove the pipe or as an alternative  create a new pipe for the new user instead of trying  to connect to the existing pipe owned by the previous user.

**Comment by felixfung** [comment]
Can you please try PR #152, which adds the user ID to the name of the pipe? This way one user instance of skippy-xd would not block another.

**Comment by tonywhatever** [comment]
I confirm, #152 does solve my problem.

Thank you

**Comment by felixfung** [comment]
PR merged
