### ISSUE TITLE
Client/window blacklist

### ISSUE THREAD

**Issue by vredesbyyrd** [felixfung/skippy-xd#28]
I have recently switched over from 2bwm -> awesomewm. awesomewm (along with i3, xmonad and probably many others) has a feature called scratchpad windows. Basically, a scratchpad allows you to make any window function like a dropdown terminal. Put another way - its a quick way to toggle a windows visibility from any workspace. Scratchpads can be useful for windows that are always running but you don't necessarily want visible or taking up space ie a dedicated workspace, in my case a music player and a terminal for my server.  

On awesomewm, broadly speaking this is implemented by 'mapping' and 'unmapping' the client, and setting `skip_taskbar`. As a result it's only possible for skippy to show an icon for scratchpad clients. 

A _nice to have_ feature in skippy would be a client blacklist for windows the user does not want skippy to show/manage. I assume the way to do this would be matching against blacklisted WM_CLASS names. 

Maybe the config option would look similar to how the bindings config works, just a space separated "list"

```
[blacklist]
WM_CLASS = Tilda  mpdevil
```
 
This is simply a request for a nice to have feature imo. If it's something you find worth implementing I definitely could test. 

Ps - I'm still out of town for work, but I very much look forward to trying all the work you have done for multi-monitor support.

EDIT: grammer

**Comment by felixfung** [comment]
Taking a quick look at https://youtu.be/m6zocJ5tKxw and https://github.com/felixfung/skippy-xd/blob/ed19b0731b9968e6338a8072c6cb1dce4c942b1e/src/wm.c#L612C11-L612C11 it looks like skip_taskbar may not be the issue? If skip_taskbar is set to true I am guessing scratchpad windows would be automatically filtered away.

More generally, #13 is already a task item. The code logic is easy, but having the optimal user interface is hard. E.g. do you really want to blacklist all scratchpad windows? Perhaps some users may want them to be filtered only when they are toggled off? How to cater for different different users' preferences at different use cases, to do it in the config and/or command line argument level, that's the tricky bit...

**Comment by vredesbyyrd** [comment]
> Taking a quick look at https://youtu.be/m6zocJ5tKxw and https://github.com/felixfung/skippy-xd/blob/ed19b0731b9968e6338a8072c6cb1dce4c942b1e/src/wm.c#L612C11-L612C11 it looks like skip_taskbar may not be the issue? If skip_taskbar is set to true I am guessing scratchpad windows would be automatically filtered away.

Ahh yes - I messed up here. The scratchpad implementation I am using does not have a skip_taskbar option. I could have sworn it did but nope. It's just lua code so I was able to add said option and skippy does filter out the window as you predicted. Thank you for pointing this out - and sorry for the noise. 

> More generally, https://github.com/felixfung/skippy-xd/issues/13 is already a task item. The code logic is easy, but having the optimal user interface is hard. E.g. do you really want to blacklist all scratchpad windows? Perhaps some users may want them to be filtered only when they are toggled off? How to cater for different different users' preferences at different use cases, to do it in the config and/or command line argument level, that's the tricky bit...

I did not see this task, I should have looked first! It sounds like #28 does coincidentally fall under #13 umbrella. And yes , with your example use cases, implementing a sane configuration does sound tricky. I will have to ponder on that...

**Comment by felixfung** [comment]
Is there anymore on this issue or can we close this?

**Comment by vredesbyyrd** [comment]
Nope, all good. Closing.
