### ISSUE TITLE
Reduce CPU cycle usage in paging

### ISSUE THREAD

**Issue by felixfung** [felixfung/skippy-xd#53]
Current implementation of paging tinting of highlighted paging desktop is imperfect.

The refreshing of tinting, i.e. grab the untinted desktop image, then apply tinting on top of it, is obviously important part of rendering the paging desktops. It is done here, by setting `pending_damage = true` every set number of frames:

https://github.com/felixfung/skippy-xd/blob/68d8cee73202540f3c5afa1caec187eac104fa82/src/skippy.c#L1194C4-L1194C4

When the refresh rate is too slow, it leads to "fading" visual effect, which while visually cool, is not efficient for identifying currently highlighted desktop.

When the refresh rate is too fast, it leads to lag, flickers, stutters, as well as high CPU usage.

Currently the refresh rate is close to optimal to my testing. However, the CPU usage is higher than ideal.

Arguably, the whole approach of setting `pending_damage = true` every set number of frames is a fundamentally flawed approach, and some different approach, perhaps ideally event-driven approach, could handle lags/flickers/CPU usage much better.

**Comment by ahmeteid7** [comment]
i made the tintOpacity =0 in highlight to avoid that

**Comment by felixfung** [comment]
I think flickering or lagging might not show, but high CPU usage would remain?

**Comment by felixfung** [comment]
Come to think of it, *perhaps* your environment sets your wallpaper in a way that causes flicker in skippy-xd paging mode? Would there be any way for you to test that?

**Comment by felixfung** [comment]
Closed by #62

**Comment by felixfung** [comment]
@ahmeteid7 I have made PR that fixed this issue. Would you want to try it out?

**Comment by ahmeteid7** [comment]
i tested it, it is very good, great job
