### ISSUE TITLE
please support debian deb file or appimage format file

### ISSUE THREAD

**Issue by newyorkthink** [felixfung/skippy-xd#58]

**Comment by felixfung** [comment]
Good idea. Do you have any specific goal or context in mind?

I would be busy for a while so I probably would not be able to do it soon.

**Comment by newyorkthink** [comment]
> Good idea. Do you have any specific goal or context in mind?
> 
> I would be busy for a while so I probably would not be able to do it soon.

use linuxdeploy to build appimage,
i use it build 100+ software,

![image](https://github.com/felixfung/skippy-xd/assets/87791643/849b5f1e-09c3-4932-a9c0-5cb063f47458)
:)

**Comment by felixfung** [comment]
Asking for functional deb file in https://www.antixforum.com/forums/topic/skippy-xd-window-switcher-in-antix-23/page/2/#post-136125

**Comment by newyorkthink** [comment]
> Asking for functional deb file in https://www.antixforum.com/forums/topic/skippy-xd-window-switcher-in-antix-23/page/2/#post-136125

ok, think for your looking

**Comment by felixfung** [comment]
Throwing in an ask for help: if there are any Debian based user, your contribution would be appreciated.

**Comment by tonywhatever** [comment]
> Throwing in an ask for help: if there are any Debian based user, your contribution would be appreciated.

I have created a project at: <https://github.com/tonywhatever/deb_build4skippy>. I also have created  on my local computer my own two fully functional debs which I would like to share with the community.
My biggest problem right now is: i am not savvy with Github. But we will get there.

**Comment by felixfung** [comment]
Thank you!

**Comment by tonywhatever** [comment]
All done and ready for people who want to make their own binary deb-package.

**Comment by tonywhatever** [comment]
**A link to the installable binary-package is now provided.**  Right now I consider my little project 100% completed.
I  have tested the binary on _Debian12,_ _Devuan5_ and _MX-Linux23_ and had no problems to run it .Regarding _Ubuntu_ , please read my README.md. 

May I ask you to provide a link to my little debian-packageing project in your README.md.

**Comment by felixfung** [comment]
Issue superseded by #119
