### ISSUE TITLE
Some apps minimized to panel tray still visible as "shadow" state

### ISSUE THREAD

**Issue by felixfung** [felixfung/skippy-xd#64]
Discussions from #57, #59

Apps e.g. xwininfo, stacer app, jdownloader, fdm, when minimized to xfce panel, would still be visible under skippy-xd

![image](https://github.com/felixfung/skippy-xd/assets/11221765/8bf435fa-c359-4452-b2ce-d0ff84057824)

![image](https://github.com/felixfung/skippy-xd/assets/11221765/c2a87178-8191-4679-b77d-8f498550ba74)

**Comment by felixfung** [comment]
@ahmeteid7 I find that

```
WM_STATE(WM_STATE):
		window state: Withdrawn
```

but I'm not able to find documentation on this.

Can you please try in skippy-xd config file;
```
clientList = _NET_CLIENT_LIST
```

It seems to fix the problem for me

**Comment by ahmeteid7** [comment]
that great that solved the problem with me, i tried , stacer ,fdm, Jdownloader (when hide to tray) and i tried gnome-store (when work in the background), it is very good,great job

**Comment by ahmeteid7** [comment]
if that will be solution also for :fitlers out _NET_WM_WINDOW_TYPE_POPUP_MENU
, i think it will be better than the solution that have been provided in the branch:skippy-xd-popupmenu, because i notice when try run skippy with hot corner during zorin-menu is popup, when i choose window from skippy, i need to click twice to get it

**Comment by felixfung** [comment]
I do not understand you 100%. Do you mean without branch:skippy-xd-popupmenu (now merged into master), with `clientList = _NET_CLIENT_LIST`:
1. zorin-menu will not appear under skippy-xd;
2. Single click to select window (as opposed to double-clicking?

**Comment by ahmeteid7** [comment]
yes i mean that

**Comment by felixfung** [comment]
Can you please try #67
