### ISSUE TITLE
is very problem , skippy-xd not work in i3wm, 

### ISSUE THREAD

**Issue by newyorkthink** [felixfung/skippy-xd#69]

**Comment by felixfung** [comment]
Can you please elaborate?

**Comment by newyorkthink** [comment]
> Can you please elaborate? 你能详细说明一下吗？

i3wm alt+tab not work, i test it

**Comment by felixfung** [comment]
Can you please post your skippy-xd config file, and how you set up your hot key?

Also please confirm that expose and paging works?

**Comment by newyorkthink** [comment]
> Can you please post your skippy-xd config file, and how you set up your hot key?你能发布你的skippy-xd配置文件，以及你是如何设置你的热键的吗？
> 
> Also please confirm that expose and paging works?另外，请确认曝光和分页是否有效？

i remove i3wm alt-tab ,and run skippy-xd daemon, it just not working, and cannot show anything

**Comment by felixfung** [comment]
Please see https://github.com/felixfung/skippy-xd/wiki/Config#alt-tab-setup

**Comment by newyorkthink** [comment]
> Please see https://github.com/felixfung/skippy-xd/wiki/Config#alt-tab-setup

i try it, but i3wm it ,not work

**Comment by felixfung** [comment]
Can you please post your skippy-xd config file, and how you set up your hot key?

Also please confirm that expose and paging works?

Also see https://youtu.be/R__zua04xe0?feature=shared&t=403

**Comment by newyorkthink** [comment]
> Can you please post your skippy-xd config file, and how you set up your hot key?
> 
> Also please confirm that expose and paging works?
> 
> Also see https://youtu.be/R__zua04xe0?feature=shared&t=403

sorry , i remove skippy,

can you test in i3wm

you can install i3 
sudo apt-get install i3

and logpout , the lightdm can change in i3

**Comment by felixfung** [comment]
Yes I have tested i3, alt-tab, expose, paging all works for me
