### ISSUE TITLE
disabling hot-corner during skippy preview 

### ISSUE THREAD

**Issue by ahmeteid7** [felixfung/skippy-xd#70]
although the hot-corner apps(lwa, or hot-corener plugin in xfce) has option in it's settings which it is : disable in full-screen ,but the skippy-xd not be controlled by that. so that leads to the hot-corner work during skippy-xd preview and cause strange behaviour like in the picture:
![Peek 2024-03-20 14-49](https://github.com/felixfung/skippy-xd/assets/115186023/f4620b6b-b443-42fc-8611-1cb88c6b962b)

**Comment by ahmeteid7** [comment]
i tried to disable hot-corner(lwa) while launching skippy by simple script, and it's working good until now(still test it).
#!/bin/bash

# Define the command to enable hot corners
ENABLE_HOT_CORNERS_COMMAND="lwa-hot-corners /home/eid/.config/lwa"

```
# Launch Skippy-XD in the background
skippy-xd &

# Capture the PID of Skippy-XD
SKIPPY_PID=$!

# Kill lwa-hot-corners
killall lwa-hot-corners

# Wait for Skippy-XD to finish
wait $SKIPPY_PID

# Restart lwa-hot-corners
$ENABLE_HOT_CORNERS_COMMAND
```

**Comment by felixfung** [comment]
I see the skippy-xd window is already set with override redirect flag
https://github.com/felixfung/skippy-xd/blob/7d384e18f11630207d39d45f3439f18c9f109907/src/mainwin.c#L110
and also set to fullscreen
https://github.com/felixfung/skippy-xd/blob/7d384e18f11630207d39d45f3439f18c9f109907/src/wm.c#L589

I'm curious what if you try a different hot corner method?

**Comment by ahmeteid7** [comment]
> I'm curious what if you try a different hot corner method?

i tried lwa and the hot-corner xfce plugin , i don't know any hot-corner apps for xfce, i searched but i didn't found , do you know  recommended hot-corner apps?

**Comment by felixfung** [comment]
xdotool is one way: https://youtu.be/R__zua04xe0?feature=shared&t=281

**Comment by felixfung** [comment]
@ahmeteid7 wondering if you have any updates?

**Comment by ahmeteid7** [comment]
i didn't use the xdotool , i found it is difficult to configure it in my system. i tried to use script which disable and enable hotcorner(lwa) based on the event(click action),it is worked good, but it has bad behavior and slow response sometimes, so i decide to not disable hot-corner during skippy and keep it and accept it, because it is not big problem and acceptable anyway.

**Comment by felixfung** [comment]
Should I close this issue then?

**Comment by ahmeteid7** [comment]
yes, no problem,thank you
