### ISSUE TITLE
send_command_to_daemon_via_fifo(): Failed to access() pipe "/tmp/skippy-xd-fifo-5": -1

### ISSUE THREAD

**Issue by newyorkthink** [felixfung/skippy-xd#75]
![image](https://github.com/felixfung/skippy-xd/assets/87791643/4487ae1c-3321-4536-ba47-a9ea4eb60483)
 
not work in i3wnenv

**Comment by felixfung** [comment]
Please make sure you have first done:
```
skippy-xd --start-daemon
```

**Comment by newyorkthink** [comment]
> Please make sure you have first done:
> 
> ```
> skippy-xd --start-daemon
> ```

your build is error , i allowed run 
Please make sure you have first done:

skippy-xd --start-daemon

**Comment by newyorkthink** [comment]
![image](https://github.com/felixfung/skippy-xd/assets/87791643/d4ad6771-1d8d-4594-9648-605677c23f74)

**Comment by felixfung** [comment]
Please obtain the complete config file here: https://github.com/felixfung/skippy-xd/blob/master/skippy-xd.sample.rc

**Comment by felixfung** [comment]
Lol
